# Generated by Django 5.2 on 2025-04-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("example_app", "0003_alter_book_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="number_of_pages",
            field=models.PositiveSmallIntegerField(
                blank=True, verbose_name="Number of pages"
            ),
        ),
    ]
