repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.283
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      language_version: python3.10
      args:
        - --line-length=88
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
    - id: bandit
      language_version: python3
      exclude: /tests/
