# Generated by Django 5.0.3 on 2024-04-08 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsfr", "0006_alter_dsfrconfig_accessibility_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsfrconfig",
            name="newsletter_description",
            field=models.TextField(
                blank=True, default="", verbose_name="Description de la newsletter"
            ),
        ),
        migrations.AddField(
            model_name="dsfrconfig",
            name="newsletter_url",
            field=models.URLField(
                blank=True, default="", verbose_name="URL d’inscription à la newsletter"
            ),
        ),
        migrations.AlterField(
            model_name="dsfrconfig",
            name="notice",
            field=models.TextField(
                blank=True, default="", verbose_name="Bandeau d’information importante"
            ),
        ),
        migrations.CreateModel(
            name="DsfrSocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Title"
                    ),
                ),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                (
                    "icon_class",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Icon class",
                    ),
                ),
                (
                    "site_config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dsfr.dsfrconfig",
                    ),
                ),
            ],
        ),
    ]
