# Generated by Django 4.2.15 on 2024-08-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dsfr", "0008_alter_dsfrsocialmedia_options_dsfrconfig_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsfrconfig",
            name="notice_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("info", "Information"),
                    ("warning", "Warning"),
                    ("alert", "Alert"),
                    ("weather-orange", "Orange weather alert"),
                    ("weather-red", "Red weather alert"),
                    ("weather-purple", "Purple weather alert"),
                    ("attack", "Attack alert"),
                    ("witness", "Call for witnesses"),
                    ("cyberattack", "Cyberattack"),
                ],
                help_text='Use is strictly regulated, see <a href="https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/bandeau-d-information-importante/">documentation</a>.',
                max_length=20,
                verbose_name="Notice type",
            ),
        ),
        migrations.AlterField(
            model_name="dsfrconfig",
            name="notice",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The important notice banner should only be used for essential and temporary information.             (Excessive or continuous use risks “drowning” the message.)",
                verbose_name="Important notice content",
            ),
        ),
    ]
