import warnings
from pathlib import Path

import django
from django import forms
from django.forms.renderers import DjangoTemplates, get_default_renderer
from django.utils.functional import cached_property
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from dsfr.utils import dsfr_input_class_attr


class DsfrDjangoTemplates(DjangoTemplates):
    @cached_property
    def engine(self):  # type: ignore
        return self.backend(
            {
                "APP_DIRS": True,
                "DIRS": [
                    Path(__file__).resolve().parent / self.backend.app_dirname,
                    Path(forms.__path__[0]).resolve() / "templates",  # type: ignore
                ],
                "NAME": "djangoforms",
                "OPTIONS": {},
            }  # type: ignore
        )


class DsfrBoundField(forms.BoundField):
    if django.VERSION < (5, 0):
        """
        Compatibility with Django<5.0
        https://docs.djangoproject.com/en/5.0/ref/forms/api/#django.forms.BoundField.as_field_group
        """

        def as_field_group(self):
            return self.render()

    @property
    def template_name_help_text(self):
        return next(
            template
            for it in (self.field.widget, self.field, self.form)
            if (template := getattr(it, "template_name_help_text", None))
        )

    @property
    def template_name(self):
        template_name = self.field.template_name or getattr(
            self.field.__class__, "template_name", None
        )
        if template_name:
            return template_name

        match self.widget_type:
            case "checkbox":
                return "dsfr/form_field_snippets/checkbox_snippet.html"
            case "checkboxselectmultiple" | "inlinecheckboxselectmultiple":
                return "dsfr/form_field_snippets/checkboxselectmultiple_snippet.html"
            case "radioselect" | "inlineradioselect":
                return "dsfr/form_field_snippets/radioselect_snippet.html"
            case "richradioselect":
                return "dsfr/form_field_snippets/richradioselect_snippet.html"
            case "numbercursor":
                return "dsfr/form_field_snippets/numbercursor_snippet.html"
            case "segmentedcontrol":
                return "dsfr/form_field_snippets/segmented_control_snippet.html"
            case _:
                return "dsfr/form_field_snippets/input_snippet.html"

    @property
    def label(self):
        from django.conf import settings

        try:
            mark_optional_fields = settings.DSFR_MARK_OPTIONAL_FIELDS
        except AttributeError:
            mark_optional_fields = False

        if not mark_optional_fields:
            warnings.warn(
                """Marking required form fields is not recommended by DSFR anymore
                (https://www.systeme-de-design.gouv.fr/version-courante/fr/modeles/blocs-fonctionnels/formulaires#champ-obligatoire)
                so the next major version of django-dsfr will stop doing so,
                and mark optional fields instead.
                To get the future behavior, you can set the transitional Django setting DSFR_MARK_OPTIONAL_FIELDS to True,
                or you can override the DSFR_MARK_OPTIONAL_FIELDS context variable of single forms,
                by overriding YourFormClass.get_context()""",
                DeprecationWarning,
            )

        marker = ""
        if self.field.required and not mark_optional_fields:
            marker = '<span class="fr-required-marker" aria-hidden="true"> *</span>'
        elif not self.field.required and mark_optional_fields:
            marker = f" {_('(Optional)')}"

        return mark_safe(  # nosec B308, B703 — output not generated by user
            f"{self.__label}{marker}"
        )

    @label.setter
    def label(self, value):
        self.__label = value

    def __init__(self, form, field, name):
        self.__label = ""
        super().__init__(form, field, name)

    def label_tag(self, contents=None, attrs=None, label_suffix=None, tag=None):
        attrs = attrs or {}
        widget_attrs = getattr(self.field.widget, "dsfr_label_attrs", {})
        for k, v in widget_attrs.items():
            attrs[k] = f"{attrs.get(k, '')} {v}".strip()

        use_legend = self.use_fieldset and tag == "legend"

        attrs.setdefault(
            "class",
            (
                "fr-fieldset__legend fr-fieldset__legend--regular"
                if use_legend
                else "fr-label"
            ),
        )

        if self.auto_id and use_legend:
            attrs.setdefault("id", f"{self.auto_id}-legend")

        return super().label_tag(contents, attrs, label_suffix, tag)

    def help_text_tag(self, attrs=None):
        attrs = attrs or {}
        if self.auto_id and not self.is_hidden:
            attrs.setdefault("id", f"{self.id_for_label}_helptext")
        attrs.setdefault("class", "fr-hint-text")
        return self.form.render(
            self.template_name_help_text, {"field": self, "attrs": attrs}
        )


class DsfrBaseForm(forms.Form):
    """
    A base form that adds the necessary classes on relevant fields
    """

    template_name = "dsfr/form_snippet.html"  # type: ignore
    template_name_label = "dsfr/forms/label.html"
    template_name_help_text = "dsfr/forms/help_text.html"
    bound_field_class = DsfrBoundField

    @property
    def default_renderer(self):  # type: ignore
        from django.conf import settings, global_settings

        return (
            DsfrDjangoTemplates  # Settings wasn't modified
            if settings.FORM_RENDERER == global_settings.FORM_RENDERER
            else get_default_renderer()
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            dsfr_input_class_attr(visible)

    if django.VERSION < (5, 2):
        """
        Compatibility with Django<5.2
        https://docs.djangoproject.com/en/5.2/releases/5.2/#simplified-override-of-boundfield
        """

        def __getitem__(self, name):
            try:
                field = self.fields[name]
            except KeyError:
                raise KeyError(
                    "Key '%s' not found in '%s'. Choices are: %s."
                    % (
                        name,
                        self.__class__.__name__,
                        ", ".join(sorted(self.fields)),
                    )
                )
            if name not in self._bound_fields_cache:
                bound_field_class = getattr(
                    self, "bound_field_class", self.bound_field_class
                )
                self._bound_fields_cache[name] = bound_field_class(self, field, name)
            return self._bound_fields_cache[name]

    def set_autofocus_on_first_error(self):
        """
        Sets the autofocus on the first field with an error message.
        Not included in the __init__ by default because it can cause some side effects on
        non-standard fields/forms.
        """
        for field in self.errors.keys():
            self.fields[field].widget.attrs.update({"autofocus": ""})
            break
