name: Django-DSFR CI for python 3.10 and 3.11

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: 🐍 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: 👷 Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: 🧪 Run Tests - Django 3
      run: |
        poetry run python manage.py test
    - name: 🧪 Run Tests - Django 4
      run: |
        poetry add django@^4.1
        poetry run python manage.py test
    - name: 🧪 Run Tests - Django 5
      run: |
        sed -i 's/python = "^3.8"/python = "^3.10"/g' pyproject.toml
        poetry add django@^5.0
        poetry run python manage.py test
